import Head from 'next/head';
import Image from 'next/image';

import Default from '../layouts/Default';
import styles from '../styles/About.module.css';

export default function work() {
	return (
		<>
			<Head>
				<title>Jane Doe - About</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.favicon.png" />
			</Head>
			<Default>
				<div className={styles.container}>
					<div className={styles.image}>
						<a>
							<Image src="/about.jpeg" alt="img" height={600} width={400} />
						</a>
					</div>
					<div className={styles.about}>
						<p>
							Jane Doe is a contemporary painter who lives and works in City,
							State. Her distinctive personal style emanates joy and peace and
							expresses the vibrant spirit and atmosphere of the Caribbean
							culture. Picturesque landscapes, tropical birds and flowers,
							musical instruments, and farmers tending to their fields are all
							brought to life with contrasting and harmonious colors and bold
							compositions. As the artist explains, “I am a story teller and I
							welcome you to join me on this visual journey.” As a child Doe
							received prizes for her innate talent. From a young age she has
							believed, “You can create anything once you see it in your mind.”
							She earned a Bachelor of Science in Architecture from Some
							University and Master of Landscape Architecture and Urban Planning
							from Some Other University — with honors. She is also the
							recipient of various Awards from the This Gallery in This Place.
							Doe's artwork has been shown in exhibitions in This Place and the
							U.S., including “Artwork Title”, and This Exhibition at This Show,
							Houston, TX. One of her paintings was featured at the This
							Festival. She is a member of the invitational Artist Group
							Showcase Gallery, a curated art program that rewards artistic
							excellence, in This City. She has also served as a juror in Some
							Art Prestige Club in This City.
						</p>
					</div>
				</div>
			</Default>
		</>
	);
}
