import { useRef } from 'react';
import Head from 'next/head';
import emailjs from 'emailjs-com';

import Default from '../layouts/Default';
import styles from '../styles/Contact.module.css';

export default function ContactUs() {
	const form = useRef();

	// In order for the EmailJS to Worker, you must sign up and create a template at https://https://www.emailjs.com/
	const sendEmail = (e) => {
		e.preventDefault();

    emailjs
      // The Service ID, Template Name, and Public Key are all found in your EmailJS dashboard
			.sendForm('[service_id]', '[template_name]', form.current, '[public_key]')
			.then(
				(res) => {
					alert(res.text);
				},
				(error) => {
					alert(error.text);
				}
			);
	};

	return (
		<>
			<Head>
				<title>Jane Doe - Contact</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.favicon.png" />
			</Head>
			<Default>
				<div className={styles.wrapper}>
					<p className={styles.page_title}>Contact</p>
          <form ref={form} onSubmit={sendEmail} className={styles.form}>
            <div className={styles.form_row}>
							<input
								required
								type="text"
								name="name"
								placeholder="Name"
								className={styles.input}
							/>
							<input
								required
								type="email"
								name="email"
								placeholder="Email"
								className={styles.input}
              />
            </div>
						<div>
							<textarea
								required
                name="message"
								className={styles.textarea}
							/>
						</div>
						<input type="submit" value="Send" className={styles.button} />
					</form>
				</div>
			</Default>
		</>
	);
}
