import Head from 'next/head';

import Artwork from '../components/Artwork';
import Default from '../layouts/Default';
import styles from '../styles/Home.module.css';

export default function Home() {
	const pathArr = [
		'/img_1.jpeg',
		'/img_2.jpeg',
		'/img_3.jpeg',
		'/img_4.jpeg',
		'/img_5.jpeg',
		'/img_6.jpeg',
		'/img_7.jpeg',
		'/img_8.jpeg'
  ];
  
	return (
		<>
			<Head>
				<title>Jane Doe</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.favicon.png" />
			</Head>
			<Default>
        <div className={styles.container}>

					{/* Add the path to your images to the array above called pathArr 
              Remeber, order matters! */}

					{pathArr.map((src) => (
            <Artwork key={id} path={src} />
					))}
				</div>
			</Default>
		</>
	);
}
